### ISSUE TITLE
EPIC: Improvements for Documents

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#448]
We have a series of improvements to our documents feature which we should work on in this Epic:

- [ ] #338 - show documents as tiles
- [ ] #433 - show file details
- [ ] #442 - allow updating of stored file
- [ ] #337 - Add documents to projects
- [ ] #307 - Add documents to tasks
- [ ] #83 - External links as documents

**Comment by dottorer** [comment]
@phillipoertel @NolanChan @jprokay @diegoaad 
First cut of new design spec is ready for review. Let me know what you think!

**Comment by NolanChan** [comment]
The spec is straightforward and looks good! Not sure if it should go on the doc, but we may also need to add possible points of testing as well
